version: '2.1'
services:

  config-server:
    build: config-server
    mem_limit: 512m
    ports:
      - "9097:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka-server:
    build: eureka-server
    mem_limit: 512m
    ports:
      - "8761:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  account-service:
    build: account-service
    mem_limit: 512m
    ports:
      - "9092:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodocker:
        condition: service_healthy

  mongodocker:
    image: mongo:4.4.2
    mem_limit: 512m
    ports:
      - "27018:27017"
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60