#Ports
server.port: 8090
#Spring cloud
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/rest/customer-service/**
          filters:
           - StripPrefix=2
           -
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/rest/account-service/**
          filters:
            - StripPrefix=2
            -
        - id: movements-service
          uri: lb://movements-service
          predicates:
            - Path=/rest/movements-service/**
          filters:
            - StripPrefix=2
#Eureka
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka