#Ports
server.port: 8090
#Spring cloud
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE/
          filters: StripPrefix=1
          predicates:
            - Path=/customer-service/**

        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE/
          filters: StripPrefix=1
          predicates:
            - Path=/account-service/**

        - id: MOVEMENTS-SERVICE
          uri: lb://MOVEMENTS-SERVICE/
          filters: StripPrefix=1
          predicates:
            - Path=/movements-service/**
#Eureka
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka