#Ports
server.port: 8090
#Spring cloud
spring:
  cloud:
    gateway:
      routes[0]:
        id: customer-service
        predicates: Path=/api/customer-service/**
        filters: StripPrefix=2
        uri: lb://customer-service

      routes[1]:
        id: account-service
        predicates: Path=/api/account-service/**
        filters: StripPrefix=2
        uri: lb://account-service

      routes[2]:
        id: movements-service
        predicates: Path=/api/movements-service/**
        filters: StripPrefix=2
        uri: lb://movements-service

      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'

    loadbalancer:
      ribbon:
        enabled: 'false'

#Eureka
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka