server.port: 9097
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/nelsonjaimes/nttdata-bc39-grupo4-project02
          search-paths: config-server/config-data
---
spring.config.activate.on-profile: docker
server.port: 8080